# ═══════════════════════════════════════
# KITTY — TERMINAL SHEIKAH
# ═══════════════════════════════════════

# ── FUENTE ──────────────────────────────
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
adjust_line_height 110%

# ── INTERFAZ ────────────────────────────
background_opacity        0.88
dynamic_background_opacity yes
window_padding_width      16
hide_window_decorations   yes
confirm_os_window_close   0
bell_on_tab               no
enable_audio_bell         no
visual_bell_duration      0.0
scrollback_lines          10000
url_style                 curly
open_url_with             firefox
detect_urls               yes
copy_on_select            yes

# ── CURSOR ──────────────────────────────
cursor                #00F0FF
cursor_text_color     #000000
cursor_shape          beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 10.0

# ── SELECCIÓN ───────────────────────────
selection_background  #FF7A00
selection_foreground  #000000

# ── COLORES BASE ────────────────────────
background  #0a1214
foreground  #e2e2d7

# ── PALETA ANSI ─────────────────────────
# Negros — Piedra Sheikah
color0  #1a2b2c
color8  #4b696d
# Rojos — Peligro / Excepciones
color1  #ff3333
color9  #ff6666
# Verdes — Resistencia / Rupias
color2  #2ecc71
color10 #58d68d
# Amarillos — Trifuerza
color3  #f1c40f
color11 #f4d03f
# Azules — Guardianes
color4  #0080FF
color12 #4da6ff
# Magentas — Cataclismo
color5  #9b59b6
color13 #af7ac5
# Cian — Energía Sheikah pura
color6  #00f0ff
color14 #76d7c4
# Blancos — Pergamino
color7  #e2e2d7
color15 #ffffff

# ── TAB BAR ─────────────────────────────
tab_bar_style                separator
tab_separator                ""
tab_title_template           " {index}: {title[:16]} "
active_tab_foreground        #000000
active_tab_background        #00F0FF
active_tab_font_style        bold
inactive_tab_foreground      #4b696d
inactive_tab_background      #0a1214
tab_bar_background           #0a1214
tab_bar_margin_height        4 4

# ── ATAJOS ──────────────────────────────
map ctrl+shift+t  new_tab_with_cwd
map ctrl+shift+w  close_tab
map ctrl+shift+l  next_tab
map ctrl+shift+h  previous_tab
map ctrl+equal    increase_font_size
map ctrl+minus    decrease_font_size
map ctrl+shift+c  copy_to_clipboard
map ctrl+shift+v  paste_from_clipboard

# ── SHELL ───────────────────────────────
shell /usr/bin/fish
