general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Fase 1 — 4 min: pantalla se atenúa (aviso Sheikah)
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# Fase 2 — 5 min: bloqueo con hyprlock
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Fase 3 — 8 min: pantalla apagada
listener {
    timeout = 480
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
